<?php if (! empty($question)) { ?>
    Total Score = <?= $user['scores']['totalScore']; ?> <br />
    Max Score = <?= $user['scores']['maxDailyScore']; ?> <br />
    Daily Score = <?= $user['scores']['dailyScore']; ?> <br />
    Remaining daily questions = <?= $config['maxDailyQuestions'] - $user['scores']['dailyAnswers']; ?>

    <h2><?= $question['content']; ?></h2>
    <form action="index.php?target=main&action=answer" method="post">
        <?php foreach ($question['answers'] as $key => $answer) { ?>
            <?= $alphabet[$key]; ?>. <input type="radio" name="answerId" value="<?= $answer['id']; ?>" /> <?= $answer['content']; ?><br />
        <?php } ?>
        <input type="hidden" name="questionId" value="<?= $question['id']; ?>"/><br />
        <input type="submit" name="answer" value="Answer"/>
    </form>
<?php } ?>


