<?php

use src\support\View;

?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="<?= $baseUrl ?>src/view/css/styles.css">
    <title>Quiz</title>
</head>
<body>

<?php echo View::partial('_header', $data); ?>

<?php echo View::partial('_content', array_merge($data, array('view' => (isset($view) ? $view : null)))); ?>

</body>
</html>